<?php 
define('_ROLES','Role(s)');
define('_LIEUX','Lieux');
define('_CIN','C.I.N');
define('_ECOLE','Ecole');
define('_PRECEDENTE','pr&eacute;edente');
define('_RETARDS','Retards');
define('_JUSTIFIER','Justifier');
define('_EDUCATRICES','Educatrice(s)');
define('_POLITESSE','Politesse');
define('_FONCTION','Fonction');
define('_FORMATEUR','Formateur');
define('_VACATAIRE','Vacataire');
define('_EMBAUCHE','embauche');
define('_ARRET','arr&ecirc;t');
define('_CNSS','C.N.S.S');
define('_RETOURE','Retour');
define('_CONGE','Cong&eacute;');
define('_DEMANDE','demande');
define('_SANS','Sans');
define('_TASKS','Taches');
define('_COURS','Cours');
define('_STATUS','Status');
define('_MANAGER','Manager');
define('_PRIORITE','Priorite');

define('_DOSSIER','Dossier');
define('_CLASSES','CLasses');
define('_ABSENCES','Absences');
define('_CHARGES','Charges');
define('_EMPLOYES','Employe');
define('_CONGES','Cong&eacute;s');
define('_TRESORIE','Tr&eacute;sorie');
define('_RESOURCES','Ressource');
define('_HUMAINES','humaine');
define('_AVANCES','Avances');
define('_NOMBRE_PLACES','Nombre de places');
define('_DECONNEXION','Deconnexion');
define('_MENTION','Mention');
define('_ANCIENNE','Ancienne');
define('_NOUVELLE','Nouveau');
define('_CLIENT','Client');
define('_SITAUTION','Situation');
define('_REEL','R&eacute;el');
define('_PREVISIONNEL','Previsionnel');
define('_RAISON','Raison');
define('_SOCIAL','Social');
define('_GSM','GSM');
define('_FIX','Fix');
define('_COMMERCIAL','Commercial');
define('_POST','Post');
define('_MODULE','Module');
define('_PU','P.U');
define('_RECHERCHER','Rechercher');
define('_TABLEAU','Tableau');
define('_RAPPORTS','Rapports');
define('_COMMENDER','Commender');
define('_DEBITEURS','Debiteurs');
define('_POURCENTAGE','pourcentage');
define('_FONCTIONNALITES','Fonctionnalit&eacute;s');
define('_SUIVIS','Suivis');
define('_COMMERCIAUX','Commerciaux');
define('_REGLER','R&eacute;gler');
define('_COMPTABILITES','Comptabilit&eacute;(s)');
define('_APPELS','Appel T&eacute;l&eacute;phonique');
define('_DEPLACEMENTS','D&eacute;placement');
define('_REMARQUE','Remarque');
define('_COUT','Coût');
define('_FACTURE','Facture');
define('_NBRFONCTIONNALITE','Nombre Fonctionnalit&eacute;es	');
define('_VERSION','&copy; 2010 - (18/05/2010)');
define('_QUITTER','Quitter');
define('_PARAM','Param&egrave;trages');
define('_AJOUTER','Ajouter');
define('_MODIFIER','Mettre &agrave; jour');
define('_SUPPRIMER','Supprimer');
define('_OP','Op&eacute;ration(s)');
define('_LISTE','Liste');
define('_CONNEXION','Connexion');
define('_NOM','Nom');
define('_PRENOM','Pr&eacute;nom');
define('_EMAIL','Email');
define('_NB','Nombre');
define('_LOGIN','Login');
define('_PASSWORD','Code confidentiel');
define('_FACTURES','Factures');
define('_VIDE','<div class="warning">El&eacute;ments de donn&eacute;es vide !</div>');
define('_CONTACTS','Contact(s)');
define('_MENU_ADMIN','Menu admin.');
define('_CATEGORIES','Cat&eacute;gorie(s)');
define('_CARACTERISTIQUES','Caract&eacute;ristique(s)');
define('_LIBELLE','Libell&eacute;');
define('_ENVOYER','Envoyer');
define('_LISTES','Liste(s)');
define('_CHAINE','Chaine');
define('_VILLE','Ville');
define('_CONTRAT','Contrat');
define('_ETAT','Etat');
define('_RECHERCHE','Recherche');
define('_TYPE','Type');
define('_VALEUR','Valeur');
define('_SOCIETE','Soci&eacute;t&eacute;');
define('_PAYS','Pays');
define('_QUARTIER','Quartier');
define('_ADRESSE','Adresse');
define('_IMAGE','Image');
define('_CLASSIFICATION','Classification');
define('_RC','Registre de Commerce');
define('_PATENTE','Patente');
define('HEURE','Heure');
define('DEPART','D&eacute;part');

//Les messages
define('_AJOUT_OK','L\'ajout a &eacute;t&eacute; effectu&eacute; avec succ&egrave;s.');
define('_AJOUT_NOK','L\'ajout a &eacute;chou&eacute; !');
define('_SUPPRESSION_OK','Suppression &eacute;ffectu&eacute;e avec succes');
define('_SUPPRESSION_NOK','Suppression a &eacute;chou&eacute;e !');
define('_MODIFICATION_OK','Modification effectu&eacute;e avec succ&egrave;s');
define('_MODIFICATION_NOK','Erreur lors de la modification !');
define('_ERREUR_LOGIN','Param&egrave;tes de connexion incorrects !');
define('_ERREUR_PROFIL','Votre profil est incomplet, veuillez contacter votre administrateur !');
//Fin Messages

define('_DESC','Description');
define('_PHOTOS','Photos');
define('_MENU','Menu');
define('_CHAMBRES','Chambre(s)');
define('_TITRE','Titre');
define('_REDIRECT','Veuillez patienter ...');
define('_TEL','Tel.');
define('_FAX','Fax');
define('_MODIFICATION','Modification');
define('_COMPTABILITE','Comptabilit&eacute;');
define('_ADMINISTRATION','Administration.');
define('_FICHES','Fiche(s)');
define('_HISTORIQUE','Historique');
define('_FILTRE','Filtre');
define('_UTILISATEURS','Utilisateurs');
define('_INFOS_GENERALES','Infos. G&eacute;n&eacute;rales');
define('_LOCALISATION','Localisation');;
define('_GALERIE','Galerie d\'images');
define('_DELAI','Delai');
define('_ANNULATION','Annulation');
define('_SECRETAIRE','Secretaire(s)');
define('_PARTENAIRE','Partenaire(s)');
define('_TABLES','Table(s)');
define('_JOURS','Jour(s)');
define('_DESCRIPTION','Description');
define('_LEGENDE','Legende');
define('_CLIENTS','Client(s)');
define('_NOMBRE','Nb.');
define('_DEPART','D&eacute;part');
define('_ETATS','Etat');
define('_MONTANT','Montant');
define('_PERIODE','P&eacute;riode');
define('_TARIFS','Tarif(s)');
define('_PENSION','Pension');
define('_DEFINIR','Definir');
define('_GESTION','Gestion');
define('_VALIDER','Valider');
define('_DATE','Date');
define('_DEBUT','Debut');
define('_FIN','Fin');
define('_L','L');
define('_M','M');
define('_J','J');
define('_V','V');
define('_S','S');
define('_D','D');
define('_JANVIER','Janvier'); 
define('_FEVRIER','Fevrier'); 
define('_MARS','Mars'); 
define('_AVRIL','Avril'); 
define('_MAI','Mai'); 
define('_JUIN','Juin'); 
define('_JUILLET','Juillet'); 
define('_AOUT','Aôut'); 
define('_SEPTEMBRE','Septembre'); 
define('_OCTOBRE','Octobre'); 
define('_NOVEMBRE','Novembre'); 
define('_DECEMBRE','Decembre'); 
define('_LUNDI','Lundi');
define('_MARDI','Mardi');
define('_MERCREDI','Mercredi');
define('_JEUDI','Jeudi');
define('_VENDREDI','Vendredi');
define('_SAMEDI','Samedi');
define('_DIMANCHE','Dimanche');
define('_CODES','Codes');
define('_ACCES','Acc&egrave;s');
define('_PAYS_VILLE','Pays - Ville');
define('_INFO_BANQUAIRE','Coordonn&eacute;e(s) Banquaire(s)');
define('_CONFIRMER','Confirmer');
define('_ANNULER','Annuler');
define('_DETAILS','D&eacute;tails');
define('_DESTINATIONS','Destinations');
define('_MENU_ANNEXE','Menu Annexe');
define('_DEVENIR','Devenir');
define('_CONTACT','Contact');
define('_ACCUEIL','Accueil');
define('_INDICATION','Les champs marqu&eacute;s en (*) sont obligatoires !');
define('_RECHERCHE_DETAILLEE','Recherche d&eacute;taill&eacute;e');
define('_PERSONNES','Personne(s)');
define('_COMPTE','Compte');
define('_ADMIN','Admin.');
define('_SUPPRIMEES','Supprim&eacute;(es)');
define('_EMAIL_EXISTANT','Adresse Email Existante !');
define('_AJOUT','Ajout');
define('_SUPPRESSION','Suppression');
define('_TABLE','Table');
define('_INITIALISER','Initialiser(s)');
define('_ACTUEL','Actuel');
define('_CREER','Cr&eacute;er');
define('_NEW','Nouveau');
define('_RETAPER','Retaper');
define('_ANCIEN','Ancien');
define('_TOUT','Tout');
define('_AFFICHER','Afficher');
define('_DUREE','Dur&eacute;e');
define('_ASSOCIER','Associer');
define('_ANNEES','Ann&eacute;e(s)');
define('_MOIS','Mois');
define('_SUIVANT','Suivant');
define('_TRI','Tri');
define('_DATES','Date(s)');
define('_ENTRE','Entre');
define('_ET','et');
define('_ENVOI_OK','Message envoy&eacute; avec succes');
define('_ENVOI_NOK','Message non envoy&eacute; !');
define('_STATS','Statistiques');
define('_PUBLIQUE','Publique');
define('_FICHE','Fiche');
define('_NUITS','nuit(s)');
define('_TOTAL','Total');
define('_TOTAUX','Totaux');
define('_COORDONNEES','Coordonn&eacute;es');
define('_MOBILE','Mobile');
define('_COMISSION','Comission');
define('_INITIALISATION','Initialisation ');
define('_ETAPE','&eacute;tape');
define('_COMMENTAIRES','Commentaires');
define('_CODE_POSTAL','Code postal');
define('_CIVILITE','Civilit&eacute;');
define('_BANQUE','Banque');
define('_DESIGNATION','D&eacute;signation');
define('_IMPRIMER','Imprimer');
define('_ENTITE','Entit&eacute;');
define('_EN_COURS_VALIDATION','En cours de validation');
define('_ACCEPTEE','Accept&eacute;e');
define('_REFUSEE','Refus&eacute;e');
define('_ANNEES_SCOLAIRES','Ann&eacute;e scolaire');
define('_CYCLES','Cycle(s)');
define('_NIVEAUX','Niveaux');
define('_GROUPES','Groupe(s)');
define('_TESTS','Test(s)');
define('_FRAIS','Frais');
define('_SCOLARITE','Scolarit&eacute;');
define('_SALLES','Salles');
define('_TRANSPORT','Transport');
define('_GARDE','Garde');
define('_MATIERES','Mati&egrave;re(s)');
define('_ENTREE','Entr&eacute;e');
define('_DOSSIERS','Dossier(s)');
define('_INSCRIPTION','Inscription(s)');
define('_INSCRIPTION2','Inscr.');
define('_PIECES','Pi&egrave;ce(s)');
define('_COMMUNES','Commune(s)');
define('_SPECIFIQUES','Sp&eacute;cifique(s)');
define('_HEURE','Heure(s)');
define('_H','h');
define('_ELEVES','El&egrave;ves');
define('_RENSEIGNEMENTS','Renseignement(s)');
define('_CNES','C.N.E');
define('_CNES2','Code National');
define('_SEXES','Sexe');
define('_NAISSANCES','Naissance');
define('_FRERES','Fr&egrave;re(s)');
define('_SOEURS','Soeur(s)');
define('_DOMICILES','Domicile(s)');
define('_TELEPHONE','T&eacute;l&eacute;phone');
define('_PROFESSION','Profession');
define('_PARENTS','Parent(s)');
define('_URGENCES','Urgence');
define('_PERE','P&egrave;re(s)');
define('_MERE','M&egrave;re(s)');
define('_MALADIES','Maladie(s)');
define('_DIFFICULTES','Difficult&eacute;(s)');
define('_DIFFICULTES_SCOLAIRES','Difficult&eacute;(s) scolaire(s)');
define('_HORAIRES','Horaire(s)');
define('_FEMININ','Feminin');
define('_MASCULIN','Masculin');
define('_MEDECINS','M&eacute;decin(s)');
define('_ACTIVES','Active(s)');
define('_PREINSCRIPTION','Pr&eacute;-inscription(s)');
define('_NOTES','Note(s)');
define('_RESULTATS','Resultat(s)');
define('_INSCRIPTIONS','Inscription(s)');
define('_REGLEMENTS','R&eacute;glement(s)');
define('_PERSONNEL','Personnel');
define('_SITE','Site Web');
define('_OBLIGATOIRES','Oblig.');
define('_NON_DEFINIE','Non d&eacute;finie !');
define('_PLAN','Plan');
define('_ELEMENTS','Element(s)');
define('_LIENS','Lien(s)');
define('_MENUS','Menu(s)');
define('_URL','URL');
define('_PROFILS','Profil(s)');
define('_DROITS','Droit(s)');
define('_PAGE_DEFAUT','Page par defaut');
define('_ERREUR_PARAM','Erreur de param&egrave;trage, veuillez contacter votre administrateur !');
define('_DEVISE','DH');
define('_OBLIGATOIRE','Oblig.');
define('_DECISIONS','D&eacute;sicions');
define('_MOTIFS','Motif(s)');
define('_OPTION','En option');
define('_ACCEPTE','Accept&eacute;');
define('_REJETE','Rejet&eacute;');
define('_REJETEES','Rejet&eacute;e(s)');
define('_TYPES','Type(s)');
define('_MENSUEL','Mensuel');
define('_TRIMESTRIEL','Trimestriel');
define('_ANNUEL','Annuel');
define('_REDUCTIONS','R&eacute;duction(s)');
define('_ORDRE','Ordre');
define('_RECETTE','Recette(s)');
define('_DEPENSES','D&eacute;penses');
define('_PREVISIONNELLES','Pr&eacute;visionnelle(s)');
define('_EFFECTIVES','Effective(s)');
define('_IMPAYES','Impay&eacute;(es)');
define('_PAGE','Page');
define('_DEFINITIONS','D&eacute;finition(s)');
define('_ETABLISSEMENT','Mon &eacute;tablissement');
define('_MODULES','Module(s)');
define('_WEB','Site(s) Web');
define('_NOUVEAU','Nouveau');
define('_RETAPEZ','Retaper');
define('_CODE','Code');
define('_DEFINIR_ANNEE_ACTIVE','Veuillez d&eacute;finir l\'ann&eacute;e en cours !');
define('_SYSTEMES','Syst&egrave;me(s)');
define('_HEAD','Head');
define('_FOOT','Foot');
define('_CONN','conn.');
define('_MESSAGE_DECISIONS','Veuillez mettre &agrave; jour la d&eacute;cision concernant cet &eacute;l&egrave;ve pour pouvoir activer l\'inscription');
define('_VILLES','Ville(s)');
define('_PHOTO','Photo');
define('_CAISSE','Caisse');
define('_JOURNAL','Journal');
define('_ACTIONS','Action(s)');
define('_CONNEXIONS','Connexion(s)');
define('_STATISTIQUES','Statistique(s)');
define('_ERREUR_PREINSCRIPTION','Les pr&eacute;inscriptions en attente');
define('_DERNIERES','Derni&egrave;re(s)');
define('_COMMUNS','Commun(s)');
define('_INCOMPLET','Incomplet(s)');
define('_REDUCTION','R&eacute;duction(s)');
define('_ANNUELLE','Annuelle(s)');
define('_ENCAISSER','Encaisser');
define('_DERNIERS','Dernier(s)');
define('_ENCAISSEMENTS','Encaissement(s)');
define('_RETARDATAIRES','Retardataire(s)');
define('_NATURES','Nature(s)');
define('_FOURNISSEURS','Fournisseur(s)');
define('_RAISONS','Raison(s)');
define('_SOCIALES','Sociale(s)');
define('_IMPORTER','Importer');
define('_IMPORTES','Import&eacute;(s)');
define('_NON_IMPORTES','Non Import&eacute;(s)');
define('_FICHIER','Fichier');
define('_CSV','CSV');
define('_EN_ATTENTE','En attente');
define('_TRANSPORTS','Transport(s)');
define('_TRAJETS','Trajet(s)');
define('_PRIX','Prix');
define('_FINANCE','Finance');
define('_BANQUES','Banque(s)');
define('_CAISSES','Caisse(s)');
define('_COMPTES','Compte(s)');
define('_MODE','Mode');
define('_DOCUMENT','Document');
define('_DOCUMENTS','Document(s)');
define('_N','N°');
define('_CHEQUES','Ch&egrave;que(s)');
define('_ESPECES','Esp&egrave;ce');
define('_VIREMENT','Virement bancaire');
define('_INITIAL','Initial');
define('_RIB','R.I.B');
define('_VISUALISER','Visualiser');
define('_FILTRES','Filtre(s)');
define('_ERREUR_DROITS','<div class="erreur">Vous n\'&ecirc;tes pas autoris&eacute; &agrave; visualiser cette page !</div>');
define('_ENCAISSEMENT','Encaissement');
define('_JOURNALIERES','Journali&egrave;re(s)');
define('_MENSUELLES','Mensuelles');
define('_ANNUELLES','Annuelle(s)');
define('_ETABLISSEMENTS','Etablissement');
define('_PERSONNELS','Personnel(s)');
define('_TRACES','Trace(s)');
define('_ORDRES','Ordre(s)');
define('_STAT','Statistique(s)');
define('_SCOLAIRES','Scolaire(s)');
define('_INSCRIPTION_REJETEE','La demande d\'inscription de cet &eacute;l&egrave;ve &agrave; &eacute;t&eacute; rejet&eacute;e pour les motifs pr&eacute;sent&eacute;s ci-apr&egrave;s :');
define('_REGLE','R&eacute;gl&eacute;');
define('_RESTE','Reste');
define('_IMPRESSION','Impression');
define('_WORD','Word');
define('_EXCEL','Excel');
define('_PARENTES','Parent&eacute;(s)');
define('_FI','F.I');
define('_FS','F.S');
define('_WARNING_REDUCTION','La r&eacute;duction n\'est plus param&egrave;trable car l\'&eacute;l&egrave;ve &agrave; d&eacute;j&agrave; r&eacute;gl&eacute; un mois de scolarite !');
define('_ALIMENTATIONS','Alimentation(s)');
define('_VIREMENTS','Virement(s)');
define('_SOURCE','Source');
define('_DESTINATION','Destination');
define('_PROPRIETAIRE','Propritaire');
define('_POSTES','Poste(s)');
define('_RS','R.S');
define('_PRODUITS','Produit(s)');
define('_SERVICES','Service(s)');
define('_CANTINE','Cantine');
define('_SUPPLEMENT','Suppl&eacute;ment(s)');
define('_PREMIER','Premier');
define('_DEF_MOIS_OBLIGATOIRES','Les mois dont le r&eacute;gelement est obligatoire au moment de l\'inscription');
define('_DEF_MOIS_SCOLARITE','Les mois de scolarit&eacute;');
define('_DEF_PREMIER','Le premier mois de l\'ann&eacute;e scolaires');
define('_DEF_DOCUMENT','Ch&egrave;que ou ordre de virement...');
define('_ECHEANCE','Ech&eacute;ance');
define('_POSTE','Poste');
define('_REMISES','Remise(s)');
define('_REMISE','Remise');
define('_RECU','Reçu');
define('_RECUS','Reçu(s)');
define('_CHEQUE','Ch&egrave;que');
define('_DCHEQUE','Date_Ch&egrave;que');
define('_SITUATION','Situation');
define('_FINANCIERE','Financi&egrave;re');
define('_PREINSCRIPTION_REQUISE','Une pr&eacute;inscription est requise !');
define('_FAMILLES','Famille(s)');
define('_REFERENCE','R&eacute;f&eacute;rence');
define('_REF','Ref.');
define('_PEREMPTION','P&eacute;remption');
define('_EXISTANTS','Existant(s)');
define('_EXISTANTES','Existante(s)');
define('_STOCK','Stock');
define('_TAUX','Taux');
define('_TVA','T.V.A');
define('_HT','H.T');
define('_TTC','T.T.C');
define('_QTE','Qte');
define('_COMMANDER','Commander');
define('_DEVIS','Devis');
define('_COMMANDES','Commande(s)');
define('_VALIDE','Valid&eacute;');
define('_FACTURER','Facturer');
define('_FACTUREE','Factur&eacute;(e)');
define('_CLOTURER','Cloturer');
define('_VEHICULES','V&eacute;hicule(s)');
define('_ASSURANCE','Assurance');
define('_ACTIVER','Activer');
define('_HEURES','Heure');
define('_MINUTES','Minutes');
define('_MENSUALITE','Mensualit&eacute;');
define('_POINTS','Point(s)');
define('_MENSUELS','Mensuel(s)');
define('_PASSAGE','Passage');
define('_CMD','Command&eacute;(es)');
define('_CSM','Consomm&eacute;(es)');
define('_POURCENT','Poucent. %');
define('_CLUBS','Club Sportif');
define('_MANUELS','Manuel(s)');
define('_ANNUELS','Annuel(s)');
define('_MARQUES','Marque(s)');
define('_MODELES','Mod&egrave;le(s)');
define('_IMMATRICULATION','Immatriculation');
define('_QUANTITE','Quantit&eacute;');
define('_VENDUS','Vendu(s)');
define('_MATIN','Matin');
define('_SOIR','Apr&egrave;s midi');
define('_RETOUR','Retour');
define('_ALLER','Aller');
define('_ARCHIVES','Archive(s)');
define('_ACTIVE','Activ&eacute;');
define('_DESACTIVER','D&eacute;sactiver');
define('_VEUILLEZ_SPECIFIER_MONTANT','Veuillez sp&eacute;cifier un montant sup&eacute;rieur &agrave; 0 !');
define('_RED','Red.');
define('_SUPPL','Suppl.');
define('_A','&agrave;');
define('_SUPERIEUR','Sup&eacute;rieur');
define('_INFERIEUR','Inf&eacute;rieur');
define('_NON_REMIS','Non remis');
define('_REMIS','Remis');
define('_IMPAYE','Impay&eacute; !');
define('_1','1');
define('_2','2');
define('_CANTINES','Cantine');
define('_VEUILLEZ','Veuillez');
define('_SPECIFIER','sp&eacute;cifier');
define('_LES','Le(s)');
define('_LE','le');
define('_LA','la');
define('_DE','de');
define('_ACTIVATION','Activation');
define('_MESSAGES','Message(s)');
define('_ENVOYES','Envoy&eacute;(s)');
define('_SOLDE','Solde');
define('_FOURNITURES','Fourniture(s)');
define('_RECEPTION','Rec&eacute;ption');
define('_BOITE','Boîte');
define('_DESTINATAIRES','Destinataire(s)');
define('_NON','Non');
define('_LUS','Lu(s)');
define('_NOUVEAUX','Nouveau(x)');
define('_EXPEDITEURS','Exp&eacute;diteur(s)');
define('_LU','Lu');
define('_JOINTES','Jointe(s)');
define('_BROUILLONS','Brouillons');
define('_MESSAGERIE','Messagerie');
define('_NON_ACTIVE','Non activ&eacute;');
define('_RESTES','Reste(s)');
define('_INSUFFISANT','Insuffisant');
define('_VEUILLEZ_AJOUTER_ALIMENTATION','Veuillez ajouter une alimentation de solde !');
define('_F','Fr.');
define('_MOTIF','Motif');
define('_SEUIL','Seuil');
define('_CONSOMMATIONS','Consommation(s)');
define('_ATTENTE','Attente');
define('_COCHER','Cocher');
define('_FICHIERS','Fichier(s)');
define('_LECTURE','Lecture');
define('_ENCAISSE','Encaiss&eacute;');
define('_NON_ENCAISSE','Non encaiss&eacute;');
define('_A_PAYER','&agrave; payer');
define('_RUBRIQUES','Rubrique(s)');
define('_ENTREES','Entr&eacute;e(s)');
define('_SORTIES','Sortie(s)');
define('_UNITAIRE','unitaire');
define('_COMMANDE','Command&eacute;');
define('_OUVERT','Ouvert');
define('_CLOTURE','Clôtur&eacute;');
define('_LIVREE','Livr&eacute;e');
define('_LIVRAISON','Livraison');
define('_DEPARTS','D&eacute;part(s)');
define('_JUSQU_A','Jusqu\'&agrave;');
define('_MESSAGE_DEPART_ELEVE','Cet &eacute;l&egrave;ve &agrave; quitt&eacute; l\'&eacute;cole');
define('_BANCAIRE','Bancaire');
define('_REMARQUES','Remarque(s)');
define('_PRELEVEMENTS','Pr&eacute;l&egrave;vement(s)');
define('_LIVREES','Livr&eacute;e(s)');
define('_COMMANDEES','Command&eacute;e(s)');
define('_RUPTURE','Rupture');
define('_CMP','C.M.P');
define('_CRENEAUX','Cr&eacute;neau(x)');
define('_LIVRAISONS','Livraison(s)');
define('_BL','B.L');
define('_ARTICLES','Article(s)');
define('_MOYENNE','Moyenne');
define('_MOYENNE2','Moy.');
define('_COEFFICIENT','Coefficient');
define('_COEF','Coef.');
define('_ABREVIATION','Abreviation');
define('_ADMIS','Admis(e)');
define('_NON_ADMIS','Non admis(e)');
define('_PLANNING','Planning');
define('_INDISPONIBLE','Indisponible');
define('_DEFINIR_PLANING','Veuillez d&eacute;finir le planning de ce test !');
define('_UTILES','Utile(s)');
define('_BULLETINS','Bulletin(s)');
define('_UNITES','Unit&eacute;(s)');
define('_DISCIPLINES','Discipline(s)');
define('_PEDAGOGIE','P&eacute;dagogie');
define('_SESSIONS','Session(s)');
define('_CONTROLES','Contrôle(s)');
define('_EXAMENS','Examen(s)');
define('_SEMESTRES','Semestre(s)');
define('_REGISTRES','Registre(s)');
define('_REG','Reg.');
define('_ENSEIGNANTS','Enseignant(s)');
define('_REPONDRE','R&eacute;pondre');
define('_ARCHIVER','Archiver');
define('_SAISIE','Saisie');
define('_DEFINIR_SEMESTRE_EN_COURS','Veuillez d&eacute;finir un semestre en cours !');
define('_PROF','Prof.');
define('_ENS','Ensg.');
define('_AGENTS','Agent(s)');
define('_AUCUN_MODELES','Veuillez d&eacute;finir un mod&egrave;le !');
define('_DEFINIR_UNITES_SCOLAIRES','Veuillez d&eacute;finir des unit&eacute;s scolaires !');
define('_DEFINIR_DISCIPLINES','Veuillez d&eacute;finir des disciplines !');
define('_DEFINIR_SEMESTRE','Veuillez d&eacute;finir des semestres !');
define('_DEFINIR_SESSIONS','Veuillez d&eacute;finir des sessions !');
define('_DEFINIR_CONTROLES','Veuillez d&eacute;finir des contrôles !');
define('_DEFINIR_MODELES','Veuillez d&eacute;finir des mod&egrave;les de registre des notes !');
define('_TMP','tmp');
define('_RELANCE','Relance');
define('_RACCOURCIS','raccourcis');
define('_DESCRIPTIF','Descriptif');
define('_PREINSCRIPTION','Pr&eacute;inscription');
define('_RAPIDE','Rapide');
define('_REINS','Reins.');
define('_ERREUR_ACTIVATION_REINSCRIPTION','Veuillez contacter votre administrateur pour activer les r&eacute;inscription !');
define('_REINSCRIPTIONS','R&eacute;inscription(s)');
define('_ERREUR_DEFINITION_CYCLES','Veuillez contacter votre administrateur pour D&eacute;finir des cycles pour l\'ann&eacute;e de r&eacute;inscription !');
define('_ERREUR_DEFINITION_NIVEAUX','Veuillez contacter votre administrateur pour D&eacute;finir des niveaux pour l\'ann&eacute;e de r&eacute;inscription !');
define('_ERREUR_DEFINITION_GROUPES','Veuillez contacter votre administrateur pour D&eacute;finir des groupes pour l\'ann&eacute;e de r&eacute;inscription !');
define('_CA','C.A');
define('_SPECIFIER_NIVEAU_ANNEE','Veuillez sp&eacute;cifier un niveau et une ann&eacute;e scolaire !');
define('_AUTRES','Autre(s)');
define('_VEUILLEZ_DEFINIR_PARENTS','Veuillez d&eacute;finir un parent !');
define('_PROFESSEURS','professeurs');
define('_FERIES','feries');
define('_NUMERO','numero');
define('_GLOBALES','globale');
define('_EXTERIEURS','exterieurs');
define('_AUTEURS','auteurs');
define('_EDITEURS','editeurs');
define('_GENRES','genres');
define('_FORMATS','format');
define('_LIVRES','livres');
define('_BOBLIOTIQUE','bibliotique');
define('_ISBN','isbn');
define('_ABONNEE','abonnee');
define('_INFORMATIONS','informations');
define('_PAIEMENTS','Paiements');
?>